{{- if .Values.crdCache.enabled }}
{{- $enabledTypes := include "wiz-admission-controller.enabledRunnerTypes" . | fromJsonArray }}
{{- range $runnerType := $enabledTypes }}
---
# NOTE: This Secret is modified at runtime by the wiz-admission-controller.
# If using ArgoCD, this will cause the application to be marked as out-of-sync.
#
# To prevent this, you have two options:
#
# Option 1: Add the following to your ArgoCD Application manifest under spec.ignoreDifferences:
#
#   - group: ""
#     kind: Secret
#     name: {{ include "wiz-admission-controller.cacheSecretName" $runnerType }}
#     namespace: {{ $.Release.Namespace }}
#     jsonPointers:
#     - /data
#
# Option 2: Set crdCache.argoCDCompatibilityMode to "helm-hook" in your values.yaml.
#            This adds Helm hooks to prevent ArgoCD from tracking this secret.
#            Note: You must manually delete this secret after uninstalling the chart.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-admission-controller.cacheSecretName" $runnerType }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "wiz-admission-controller.labels" $ | nindent 4 }}
    wiz.io/cache-type: "secret"
    wiz.io/runner-type: {{ $runnerType | quote }}
  {{- if eq $.Values.crdCache.argoCDCompatibilityMode "helm-hook" }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
  {{- end }}
type: Opaque
data:
  data: "" # Empty data that will be filled by the wiz-admission-controller
{{- end }}
{{- end }}

