{{- if .Values.crdCache.enabled }}
{{- $enabledTypes := include "wiz-admission-controller.enabledRunnerTypes" . | fromJsonArray }}
{{- range $runnerType := $enabledTypes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-admission-controller.cacheSecretName" $runnerType }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "wiz-admission-controller.labels" $ | nindent 4 }}
    wiz.io/cache-type: "secret"
    wiz.io/runner-type: {{ $runnerType | quote }}
type: Opaque
data: {}
{{- end }}
{{- end }}

