{{- if .Values.httpProxyConfiguration.enabled }}
{{- $noProxyCommaSeparatedList := join "," .Values.httpProxyConfiguration.noProxy }}
{{- $noProxySpaceSeparatedList := join " " .Values.httpProxyConfiguration.noProxy }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.httpProxyConfiguration.name }}
  labels:
    {{- include "wiz-outpost-configuration.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
data:
  httpProxy: {{ .Values.httpProxyConfiguration.httpProxy | default "" | b64enc | quote }}
  http-proxy: {{ .Values.httpProxyConfiguration.httpProxy | default "" | b64enc | quote }}
  httpsProxy: {{ .Values.httpProxyConfiguration.httpsProxy | default "" | b64enc | quote }}
  https-proxy: {{ .Values.httpProxyConfiguration.httpsProxy | default "" | b64enc | quote }}
  no-proxy-address: {{ $noProxySpaceSeparatedList | default "" | b64enc | quote }}
  no-proxy-address-cs: {{ $noProxyCommaSeparatedList | default "" | b64enc | quote }}
  noProxyAddress: {{ $noProxyCommaSeparatedList | default "" | b64enc | quote }}
  noProxyAddressSpaceSepareted: {{ $noProxySpaceSeparatedList | default "" | b64enc | quote }}
  caCertificate: {{ .Values.httpProxyConfiguration.caCertificate | default "" | b64enc | quote }}
  clientCertificate: {{ .Values.httpProxyConfiguration.clientCertificate | default "" | b64enc | quote }}
{{- end }}
