{{- if .Values.outpostController.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wiz-outpost-configuration.fullname" . }}-outpost-controller
  labels:
    {{- include "wiz-outpost-configuration.labels" . | nindent 4 }}
    app.kubernetes.io/component: outpost-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.outpostController.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end }}