# Default values for wiz-outpost-configuration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Shared values used by multiple components
outpostId: ""
clusterRegion: ""
clusterName: ""
env: ""

httpProxyConfiguration:
  enabled: false
  name: wiz-http-proxy-configuration
  # nodeConfigurationType: none # supported values: none, gcp-ubuntu
  # httpProxy: replaceme
  # httpsProxy: replaceme
  # noProxy:
  #   - replaceme
  #   - replaceme2
  # caCertificate: |
  #   ----- BEGIN CERTIFICATE -----
  #   replace me
  #   ----- END CERTIFICATE -----
  # clientCertificate: |
  #   ----- BEGIN CERTIFICATE -----
  #   replace me
  #   ----- END CERTIFICATE -----

agent:
  enabled: false
  clientId: ""
  clientSecret: ""
  privateKey: ""
  # Annotations to add to the agent secret
  annotations: {}

agentCredsSecretName: wiz-outpost-agent-creds

azureWorkerCredentials: 
  # tenantId: replaceme
  # aadClientId: replaceme
  # aadClientSecret: replaceme
  # subscriptionId: replaceme
  # environment: replaceme
  # useInstanceMetadata: false
  # useFederatedToken: false
azureWorkerCredentialsSecretName: azure-creds

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If empty, a name is generated using the fullname template
  name: ""

networkAnalyzer:
  enabled: false
  name: wiz-network-analyzer
  wizRegion: ""
  dataCenter: ""
  logsIngestionEndpoint: ""
  forceHttp1: false
  image:
    registry: public-registry.wiz.io/wiz-app
    repository: wiz-network-analyzer
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.1"
  failDeploymentOnFailure: true

  podAnnotations: {}
  imagePullSecrets: []
  resources: {}
  rollingUpdate: true
  publicRegistryEndpoints: []
  privateRegistryEndpoints: []

outpostController:
  enabled: false
  serviceAccountName: outpost-controller-sa
  # Use CA hash-based tunnel ID instead of clusterName (default: false for backward compatibility)
  useCAHashTunnelID: false
  image:
    repository: public-registry.wiz.io
    name: wiz-outpost-controller
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  resources: {}

clusterRegistrar:
  enabled: false
  name: wiz-outpost-cluster-registrar
  image:
    repository: public-registry.wiz.io
    name: wiz-outpost-cluster-registrar
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  # Single configuration object that gets passed as JSON
  config:
    cloudProvider: ""  # Required: aws, azure, gcp, or oci

    # AWS-specific configuration
    awsConfig:
      kubernetesServiceAccountName: ""
      regionalReplicaStateBucketName: ""
      regionalReplicaImageRepository: ""

    # Azure-specific configuration
    azureConfig:
      subscriptionId: ""
      resourceGroupName: ""
      diskStorageAccountNames: []
      appServiceStorageAccountNames: []
      podIdentityName: ""
      nodeResourceGroup: ""
      kubernetesServiceAccountName: ""
      subnetId: ""

    # GCP-specific configuration
    gcpConfig:
      projectId: ""
      clusterZone: ""
      nodePools: []
      # - nodePoolID: ""
      #   minSize: 1
      #   maxSize: 10

    # OCI configuration
    ociConfig:
      clusterOCID: ""
      nodePools: []
      # - nodePoolOCID: ""
      #   minSize: 1
      #   maxSize: 10

    # HTTP Proxy configuration (optional)
    httpProxyConfig:
      httpProxy: ""
      httpsProxy: ""
      vpcCIDRs: []

    # Internet access configuration (optional)
    internetAccessConfig:
      skipSslValidation: false
      trustedCA: ""

    # Storage class parameters (optional)
    storageClassParameters: {}

  failDeploymentOnFailure: true
  resources: {}

podAnnotations: {}
imagePullSecrets: []
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
