{{- if .Values.enabled }}
{{ $mountPath := "/etc/connectorData" }}
{{ $connectorDataFileName := "data" }}
{{ $connectorDataFilePath := printf "%s/%s" $mountPath "data" }}
{{ $mtlsPath := "/etc/mtls" }}
{{ $caCertificateMountPath := "/usr/local/share/ca-certificates" }}
{{ $customCertificateFileName := "ca-certificates.crt" }}
{{ $clientCertificateFileName := "client.cert" }}
{{ $clientPrivateKeyFileName := "client.key" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiz-broker.deploymentName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wiz-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.rollmeAnnotation.enabled }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        wiz.io/component: "broker"
        {{- /* `labels` includes `selectorLabels` */}}
          {{- include "wiz-broker.labels" . | nindent 8 }}
    spec:
      {{- with .Values.global.podAdditionalSpec }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.podAdditionalSpec }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wiz-broker.serviceAccountName" . }}
      securityContext:
        {{- if hasKey .Values.global "lowPrivilegePodSecurityPolicy" }}
        {{- toYaml .Values.global.lowPrivilegePodSecurityPolicy | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
        {{- end }}
      volumes:
        {{- include "wiz-broker.spec.common.volumes" . | trim | nindent 8 }}
        - name: connector-data
          secret:
            secretName: {{ include "wiz-broker.connectorSecretName" . | trim }}
            items:
              - key: connectorData
                path: {{ $connectorDataFileName }}
        {{- if .Values.caCertificate.enabled }}
        - name: ca-certificate
          secret:
            secretName: {{ include "wiz-broker.caCertificateSecretName" . | trim }}
            items:
              - key: caCertificate
                path: {{ $customCertificateFileName }}
        {{- end }}
        {{- if .Values.mtls.enabled }}
        - name: mtls
          secret:
            secretName: {{ include "wiz-broker.mtlsSecretName" . | trim }}
            items:
              - key: certificate
                path: {{ $clientCertificateFileName }}
              - key: privateKey
                path: {{ $clientPrivateKeyFileName }}
        {{- end }}
        {{- with .Values.global.customVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.customVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- if hasKey .Values.global "lowPrivilegeSecurityPolicy" }}
            {{- toYaml .Values.global.lowPrivilegeSecurityPolicy | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.global.securityContext | nindent 12 }}
            {{- end }}
          image: {{ include "wiz-broker.image" . }}
          imagePullPolicy: {{ coalesce .Values.global.image.pullPolicy .Values.image.pullPolicy }}
          volumeMounts:
          {{- include "wiz-broker.spec.common.volumeMounts" . | trim | nindent 10 }}
          - name: connector-data
            mountPath: {{ $mountPath }}
            readOnly: true
          {{- if .Values.caCertificate.enabled }}
          - name: ca-certificate
            mountPath: {{ $caCertificateMountPath }}
            readOnly: true
          {{- end }}
          {{- if .Values.mtls.enabled }}
          - name: mtls
            mountPath: {{ $mtlsPath }}
            readOnly: true
          {{- end }}
          {{- with .Values.global.customVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.customVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          args:
            - --connector-data-file-path
            - {{ $connectorDataFilePath | quote }}
          env:
          {{- if .Values.global.logLevel }}
          - name: LOG_LEVEL
            value: {{ .Values.global.logLevel }}
          {{- end }}
          - name: WIZ_ENV
            value: {{ coalesce .Values.global.wizApiToken.clientEndpoint .Values.wizApiToken.clientEndpoint | quote }}
          {{- if .Values.global.awsPrivateLink.enabled }}
          - name: USE_WIZ_PRIVATE_LINK_ENDPOINTS
            value: "true"
          {{- end }}
          {{- if not .Values.wizApiToken.usePodCustomEnvironmentVariablesFile }}
          - name: CLI_FILES_AS_ARGS
          {{- $wizApiTokensPath := "" -}}
          {{- if coalesce .Values.global.wizApiToken.wizApiTokensVolumeMount .Values.wizApiToken.wizApiTokensVolumeMount }}
          {{- $wizApiTokensPath = coalesce .Values.global.wizApiToken.wizApiTokensVolumeMount .Values.wizApiToken.wizApiTokensVolumeMount -}}
          {{- else }}
          {{- $wizApiTokensPath = printf "/var/%s" (include "wiz-common.volumes.apiClientName" .) -}}
          {{- end }}
            value: "{{ $wizApiTokensPath }}/clientToken,{{ $wizApiTokensPath }}/clientId"
          {{- end }}
          {{- if or .Values.global.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.enabled -}}
          {{ include "wiz-common.proxy.env" . | trim | nindent 10 }}
          {{- end }}
          {{- if .Values.managed.enabled }}
          - name: WIZ_MANAGED
            value: "true"
          - name: WIZ_OUTPOST_ID
            value: {{ .Values.managed.outpostId | quote }}
          - name: WIZ_ON_CALL_CLUSTER_ID
            value: {{ .Values.managed.oncallClusterID | quote }}
          {{- end }}
          - name: TARGET_IP
            value: {{ .Values.targetIp }}
          - name: TARGET_PORT
            value: {{ .Values.targetPort | quote }}
          {{- if .Values.podCustomEnvironmentVariablesFile }}
          - name: CLI_ENV_FILE
            value: {{ .Values.podCustomEnvironmentVariablesFile }}
          - name: USE_CLI_ENV_FILE
            value: "true"
          {{- end }}
          {{- if .Values.skipTlsVerify }}
          - name: DISABLE_TLS_VALIDATION
            value: "true"
          {{- end }}
          {{- if .Values.caCertificate.enabled }}
          - name: CA_CERT_PATH
            value: {{ printf "%s/%s" $caCertificateMountPath $customCertificateFileName }}
          {{- end }}
          {{- if .Values.mtls.enabled }}
          - name: CLIENT_CERT_PATH
            value: {{ printf "%s/%s" $mtlsPath $clientCertificateFileName }}
          - name: CLIENT_KEY_PATH
            value: {{ printf "%s/%s" $mtlsPath $clientPrivateKeyFileName }}
          {{- end }}
          {{- with .Values.global.podCustomEnvironmentVariables }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.podCustomEnvironmentVariables }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_DEPLOYMENT_NAME
            value: {{ include "wiz-broker.deploymentName" . }}
          {{- if or .Values.global.istio.enabled .Values.istio.enabled }}
          - name: WIZ_ISTIO_PROXY_ENABLED
            value: "true"
          - name: WIZ_ISTIO_PROXY_PORT
            value: {{ coalesce .Values.global.istio.proxySidecarPort .Values.istio.proxySidecarPort | quote }}
          {{- end }}
          - name: WIZ_CHART_VERSION
            value: "{{ .Chart.Version }}"
          {{- if .Values.global.useHATunnel }}
          - name: WIZ_USE_HATUNNEL
            value: "1"
          - name: WIZ_BROKER_HEARTBEAT_DISABLE_CLUSTER_ID
            value: "1"
          - name: WIZ_AUTO_ROLLOUT_ROLE
            value: {{ ternary "true" "false" .Values.autoRolloutUpdate | quote }}
          - name: WIZ_HEALTH_PORT
            value: {{ .Values.healthPort | quote }}
          {{- if .Values.connectorType }}
          - name: CONNECTOR_TYPE
            value: {{ .Values.connectorType | quote }}
          {{- end }}
          {{- if gt (int .Values.healthPort) 0 }}
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              port: {{ .Values.healthPort }}
              path: /ready
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 90 # 15 minutes
            httpGet:
              port: {{ .Values.healthPort }}
              path: /live
          ports:
            - containerPort: {{ .Values.healthPort }}
              name: health
          {{- end }}
          {{- end }}
          {{- include "wiz-common.renderResources" (list .Values.resources (index .Values.global "wiz-kubernetes-connector" "resources")) | nindent 10 -}}
      {{- with (coalesce .Values.global.nodeSelector .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.global.affinity .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (or .Values.global.tolerations .Values.tolerations) }}
      tolerations:
        {{- with .Values.global.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
